export const fallbackAvailableTests = [
  {
    id: 1,
    title: 'Electrical Systems Fundamentals',
    category: 'Electrical',
    difficulty: 'beginner',
    duration: 30,
    questions: 25,
    description:
      'Test your knowledge of basic electrical systems, wiring, and safety protocols.',
    skills: [
      'Circuit Analysis',
      'Wiring',
      'Safety Protocols',
      'Electrical Codes',
    ],
    certification: true,
    premium: false,
    rating: 4.8,
    completions: 1250,
    passingScore: 70,
  },
  {
    id: 2,
    title: 'Advanced Plumbing Techniques',
    category: 'Plumbing',
    difficulty: 'advanced',
    duration: 45,
    questions: 35,
    description:
      'Advanced plumbing systems, pipe fitting, and troubleshooting complex issues.',
    skills: [
      'Pipe Fitting',
      'Drain Systems',
      'Water Pressure',
      'Leak Detection',
    ],
    certification: true,
    premium: true,
    rating: 4.9,
    completions: 892,
    passingScore: 80,
  },
  {
    id: 3,
    title: 'Carpentry and Woodworking',
    category: 'Carpentry',
    difficulty: 'intermediate',
    duration: 40,
    questions: 30,
    description:
      'Comprehensive assessment of carpentry skills, tools, and techniques.',
    skills: ['Joinery', 'Tool Usage', 'Measurements', 'Wood Types'],
    certification: true,
    premium: false,
    rating: 4.7,
    completions: 1100,
    passingScore: 75,
  },
  {
    id: 4,
    title: 'HVAC Systems Mastery',
    category: 'HVAC',
    difficulty: 'expert',
    duration: 60,
    questions: 50,
    description:
      'Expert-level assessment covering complex HVAC systems and refrigeration.',
    skills: [
      'Refrigeration',
      'Air Conditioning',
      'Heating Systems',
      'Ventilation',
    ],
    certification: true,
    premium: true,
    rating: 4.9,
    completions: 567,
    passingScore: 85,
  },
];

export const fallbackCompletedAssessments = [
  {
    id: 1,
    title: 'Electrical Systems Fundamentals',
    score: 85,
    maxScore: 100,
    completedAt: '2024-01-10T10:00:00Z',
    certificate: true,
    timeSpent: 28,
    correctAnswers: 21,
    totalQuestions: 25,
  },
  {
    id: 3,
    title: 'Carpentry and Woodworking',
    score: 78,
    maxScore: 100,
    completedAt: '2024-01-05T14:30:00Z',
    certificate: true,
    timeSpent: 35,
    correctAnswers: 23,
    totalQuestions: 30,
  },
];

export const fallbackSkills = [
  {
    name: 'Electrical Wiring',
    level: 85,
    verified: true,
    category: 'Electrical',
    proficiencyLevel: 4,
  },
  {
    name: 'Carpentry',
    level: 78,
    verified: true,
    category: 'Carpentry',
    proficiencyLevel: 3,
  },
  {
    name: 'Plumbing Basics',
    level: 65,
    verified: false,
    category: 'Plumbing',
    proficiencyLevel: 3,
  },
  {
    name: 'Safety Protocols',
    level: 92,
    verified: true,
    category: 'General',
    proficiencyLevel: 5,
  },
  {
    name: 'Tool Maintenance',
    level: 73,
    verified: false,
    category: 'General',
    proficiencyLevel: 3,
  },
];

export const fallbackAnalytics = {
  totalTests: 12,
  avgScore: 81.5,
  totalTimeSpent: 420,
  certifications: 3,
  skillsVerified: 8,
  rankPercentile: 87,
  strengths: ['Electrical', 'Safety'],
  improvementAreas: ['Plumbing', 'HVAC'],
};
