name: CI/CD
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd kelmah-backend
          npm ci
      - name: Run tests
        run: |
          cd kelmah-backend
          npm test

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd kelmah-frontend
          npm ci
      - name: Run tests
        run: |
          cd kelmah-frontend
          npm test

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [backend-tests, frontend-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy via SSH and Docker Compose
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}        # Your server IP or hostname
          username: ${{ secrets.SSH_USER }}    # SSH user
          key: ${{ secrets.SSH_KEY }}         # SSH private key
          script: |
            set -e
            # Deploy backend
            cd ${{ secrets.DEPLOY_PATH }}/kelmah-backend
            docker-compose pull
            docker-compose up -d --build
            # Deploy frontend
            cd ../kelmah-frontend
            npm ci
            npm run build
            # TODO: add commands to upload or serve the frontend build artifacts 